
services:
  web:
    build: .
    container_name: codebaze_app
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env                    # optional: environment variables file
    depends_on:
      - db
    volumes:
      - ./static/uploads:/app/static/uploads

  db:
    image: mysql:8.0
    container_name: codebaze_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
