name: Deploy Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key file (.pem)
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/\\n/\n/g' > server_key.pem
          chmod 600 server_key.pem

      - name: Test SSH connection
        run: |
          ssh -i server_key.pem \
              -o StrictHostKeyChecking=no \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
              'echo "âœ… SSH connection successful"'

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: server_key.pem
          script_stop: true
          script: |
            set -e
            cd ~/codebaze-academy-backend
            git pull origin main
            docker compose down
            docker compose up -d --build
